### ISSUE TITLE
Cant install on project using Xcode 10.1 and Swift 4

### ISSUE THREAD

**Issue by ducbm051291** [uizaio/uiza-ios-sdk#3]
I have installed UizaSDK by Pod but failed because of this error

[!] CocoaPods could not find compatible versions for pod "UizaSDK":
  In Podfile:
    UizaSDK

Specs satisfying the `UizaSDK` dependency were found, but they required a higher minimum deployment target.

Please support me guys :D Thanks

**Comment by deathemperor** [comment]
Hi, @ducbm051291. Thanks for reporting.

Can you try setting `platform :ios, '8.0'` in your Podfile and then run `pod install` again?

Let me know.

**Comment by ducbm051291** [comment]
> Hi, @ducbm051291. Thanks for reporting.
> 
> Can you try setting `platform :ios, '8.0'` in your Podfile and then run `pod install` again?
> 
> Let me know.

Tks for you supporting. Im now able to install UizaSDK

**Comment by deathemperor** [comment]
Awesome. Closing this issue now.
